baseurl: "https://pannellum.org"
languagecode: "en-us"
title: "Pannellum"
pluralizelisttitles: false
pygmentscodefences: true
pygmentsuseclasses: true
disableRSS: true
canonifyurls: true
blackfriday:
  plainIDAnchors: true

params:
  pnlmbase: "https://cdn.pannellum.org"
  pnlmversion: 2.4
  pnlmversionfull: 2.4.0

publishdir: "../pnlm-gh-pages"
