baseurl: "https://pannellum.org"
languagecode: "en-us"
title: "Pannellum"
pluralizelisttitles: false
pygmentscodefences: true
pygmentsuseclasses: true
disableKinds: ["RSS", "taxonomy", "taxonomyTerm"]
canonifyurls: true
blackfriday:
  plainIDAnchors: true

params:
  pnlmbase: "https://cdn.pannellum.org"
  pnlmversion: 2.5
  pnlmversionfull: 2.5.6

publishdir: "../pnlm-gh-pages"
